//! Shell completions, and the "did you mean" that goes with them.
//!
//! Both are generated from [`COMMANDS`], the one table of what `stacked`
//! accepts, so a command added to `main.rs` and to the table is completed and
//! suggested without a second list to forget. A test holds the table to the
//! usage text, the same way `main.rs` holds the usage text to the dispatcher.
//!
//! Profile names and setting keys change on the user's machine, so the scripts
//! ask `stacked __complete profiles|config-keys` for them at completion time
//! rather than baking in whatever existed when the script was generated.

/// Every command, with its subcommands and the options it takes.
pub const COMMANDS: &[(&str, &[&str], &[&str])] = &[
    ("play", &[], &["--profile", "--no-update", "--run"]),
    ("status", &[], &["--profile"]),
    ("install", &[], &[]),
    ("update", &[], &["--force"]),
    ("versions", &["list", "available", "get", "remove"], &[]),
    ("pin", &[], &["--profile"]),
    ("unpin", &[], &["--profile"]),
    ("profiles", &["list", "new", "use"], &[]),
    ("config", &["list", "get", "set", "unset", "path"], &[]),
    ("flags", &["list", "get", "set", "unset", "import", "edit", "clear", "path"], &["--profile"]),
    ("audio-outputs", &[], &[]),
    ("plugins", &["list", "install", "remove", "enable", "disable", "grant", "revoke", "prefs", "deno"], &["--profile"]),
    ("doctor", &[], &["--offline"]),
    ("desktop", &["install", "remove", "status"], &[]),
    ("completions", &["bash", "zsh", "fish"], &[]),
    ("diagnostics", &[], &[]),
    ("help", &[], &[]),
    ("version", &[], &[]),
];

pub fn run(args: &[String]) -> u8 {
    match args.first().map(String::as_str) {
        Some("bash") => print!("{}", bash()),
        Some("zsh") => print!("#compdef stacked\nautoload -U +X bashcompinit && bashcompinit\n{}", bash()),
        Some("fish") => print!("{}", fish()),
        _ => {
            eprintln!(
                "stacked: completions needs a shell: bash, zsh or fish. For example\n  \
                 stacked completions bash > ~/.local/share/bash-completion/completions/stacked\n  \
                 stacked completions fish > ~/.config/fish/completions/stacked.fish"
            );
            return 2;
        }
    }
    0
}

/// `stacked __complete KIND`: the words a completion script offers that only
/// this machine knows.
pub fn dynamic(args: &[String]) -> u8 {
    match args.first().map(String::as_str) {
        Some("profiles") => {
            for name in cordial_shell::profile::list() {
                println!("{name}");
            }
        }
        Some("config-keys") => {
            for key in crate::cli_config::keys() {
                println!("{key}");
            }
        }
        _ => return 2,
    }
    0
}

fn bash() -> String {
    let names: Vec<&str> = COMMANDS.iter().map(|(n, _, _)| *n).collect();
    let mut cases = String::new();
    for (name, subs, opts) in COMMANDS {
        if subs.is_empty() && opts.is_empty() {
            continue;
        }
        let mut words: Vec<&str> = subs.to_vec();
        words.extend_from_slice(opts);
        cases.push_str(&format!(
            "        {name}) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words=\"{}\"; fi ;;\n",
            words.join(" ")
        ));
    }
    format!(
        r#"# bash completion for stacked. Generated by `stacked completions bash`.
_stacked() {{
    local cur=${{COMP_WORDS[COMP_CWORD]}} prev=${{COMP_WORDS[COMP_CWORD-1]}} words=""
    if [[ $prev == --profile || $prev == -p ]]; then
        words=$(stacked __complete profiles 2>/dev/null)
    elif (( COMP_CWORD == 1 )); then
        words="{names}"
    elif (( COMP_CWORD == 3 )) && [[ ${{COMP_WORDS[1]}} == config && ${{COMP_WORDS[2]}} == @(get|set|unset) ]]; then
        words=$(stacked __complete config-keys 2>/dev/null)
    elif (( COMP_CWORD == 3 )) && [[ ${{COMP_WORDS[1]}} == profiles && ${{COMP_WORDS[2]}} == use ]]; then
        words=$(stacked __complete profiles 2>/dev/null)
    elif [[ ${{COMP_WORDS[1]}} == @(plugins|flags) && ${{COMP_WORDS[2]}} == @(install|import) ]]; then
        COMPREPLY=($(compgen -f -- "$cur")); return
    else
        case ${{COMP_WORDS[1]}} in
{cases}        esac
    fi
    COMPREPLY=($(compgen -W "$words" -- "$cur"))
}}
complete -F _stacked stacked
"#,
        names = names.join(" "),
    )
}

fn fish() -> String {
    let mut out = String::from("# fish completion for stacked. Generated by `stacked completions fish`.\n");
    out.push_str("complete -c stacked -f\n");
    for (name, _, _) in COMMANDS {
        out.push_str(&format!("complete -c stacked -n __fish_use_subcommand -a {name}\n"));
    }
    for (name, subs, opts) in COMMANDS {
        if !subs.is_empty() {
            out.push_str(&format!(
                "complete -c stacked -n '__fish_seen_subcommand_from {name}; and test (count (commandline -opc)) -eq 2' -a '{}'\n",
                subs.join(" ")
            ));
        }
        for opt in *opts {
            let long = opt.trim_start_matches("--");
            let takes = if *opt == "--profile" {
                " -r -a '(stacked __complete profiles 2>/dev/null)'"
            } else if *opt == "--run" {
                " -r"
            } else {
                ""
            };
            out.push_str(&format!("complete -c stacked -n '__fish_seen_subcommand_from {name}' -l {long}{takes}\n"));
        }
    }
    out.push_str(
        "complete -c stacked -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get set unset' \
         -a '(stacked __complete config-keys 2>/dev/null)'\n",
    );
    out.push_str(
        "complete -c stacked -n '__fish_seen_subcommand_from profiles; and __fish_seen_subcommand_from use' \
         -a '(stacked __complete profiles 2>/dev/null)'\n",
    );
    out.push_str("complete -c stacked -n '__fish_seen_subcommand_from install import' -F\n");
    out
}

/// The candidate closest to `typed`, if any is close enough to be what was
/// meant.
///
/// Close enough is an edit distance of one for short words and about a third
/// of the length for longer ones: `staus` finds `status`, `fps_Cap` finds
/// `fps_cap`, and `xyzzy` finds nothing rather than whatever happens to be
/// nearest.
pub fn suggest<'a>(typed: &str, candidates: impl IntoIterator<Item = &'a str>) -> Option<&'a str> {
    let typed_lower = typed.to_ascii_lowercase();
    let limit = (typed.chars().count() / 3).max(1);
    candidates
        .into_iter()
        .map(|c| (distance(&typed_lower, &c.to_ascii_lowercase()), c))
        .filter(|(d, _)| *d <= limit)
        .min_by_key(|(d, _)| *d)
        .map(|(_, c)| c)
}

/// Levenshtein distance, over characters.
fn distance(a: &str, b: &str) -> usize {
    let b: Vec<char> = b.chars().collect();
    let mut row: Vec<usize> = (0..=b.len()).collect();
    for (i, ca) in a.chars().enumerate() {
        let mut diagonal = row[0];
        row[0] = i + 1;
        for (j, cb) in b.iter().enumerate() {
            let above = row[j + 1];
            row[j + 1] = (above + 1).min(row[j] + 1).min(diagonal + usize::from(ca != *cb));
            diagonal = above;
        }
    }
    row[b.len()]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn near_misses_are_suggested_and_nonsense_is_not() {
        let names = COMMANDS.iter().map(|(n, _, _)| *n);
        assert_eq!(suggest("staus", names.clone()), Some("status"));
        assert_eq!(suggest("udpate", names.clone()), Some("update"));
        assert_eq!(suggest("plugin", names.clone()), Some("plugins"));
        assert_eq!(suggest("PLAY", names.clone()), Some("play"));
        assert_eq!(suggest("xyzzy", names.clone()), None);
        assert_eq!(suggest("fps_Cap", ["fps_cap", "fullscreen_confine"]), Some("fps_cap"));
    }

    #[test]
    fn distance_is_levenshtein() {
        assert_eq!(distance("kitten", "sitting"), 3);
        assert_eq!(distance("", "abc"), 3);
        assert_eq!(distance("same", "same"), 0);
    }

    #[test]
    fn every_command_is_completed_and_every_script_mentions_it() {
        let bash = bash();
        let fish = fish();
        for (name, subs, _) in COMMANDS {
            assert!(bash.contains(name), "{name} missing from bash completion");
            assert!(fish.contains(&format!("-a {name}")), "{name} missing from fish completion");
            for sub in *subs {
                assert!(bash.contains(sub), "{name} {sub} missing from bash completion");
            }
        }
    }

    #[test]
    fn the_bash_script_parses() {
        // `bash -n` checks syntax without running anything. Skipped where
        // there is no bash, which is not a failure of the script.
        let Ok(mut child) = std::process::Command::new("bash")
            .arg("-n")
            .stdin(std::process::Stdio::piped())
            .spawn()
        else {
            return;
        };
        use std::io::Write;
        child.stdin.take().unwrap().write_all(bash().as_bytes()).unwrap();
        assert!(child.wait().unwrap().success(), "bash -n rejected the completion script");
    }
}
