# bash completion for stacked. Generated by `stacked completions bash`.
_stacked() {
    local cur=${COMP_WORDS[COMP_CWORD]} prev=${COMP_WORDS[COMP_CWORD-1]} words=""
    if [[ $prev == --profile || $prev == -p ]]; then
        words=$(stacked __complete profiles 2>/dev/null)
    elif (( COMP_CWORD == 1 )); then
        words="play status install update versions pin unpin profiles config flags audio-outputs plugins doctor logs desktop completions diagnostics help version"
    elif (( COMP_CWORD == 3 )) && [[ ${COMP_WORDS[1]} == config && ${COMP_WORDS[2]} == @(get|set|unset) ]]; then
        words=$(stacked __complete config-keys 2>/dev/null)
    elif (( COMP_CWORD == 3 )) && [[ ${COMP_WORDS[1]} == profiles && ${COMP_WORDS[2]} == @(use|remove) ]]; then
        words=$(stacked __complete profiles 2>/dev/null)
    elif [[ ${COMP_WORDS[1]} == @(plugins|flags) && ${COMP_WORDS[2]} == @(install|import) ]]; then
        COMPREPLY=($(compgen -f -- "$cur")); return
    else
        case ${COMP_WORDS[1]} in
        play) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--profile --no-update --run"; fi ;;
        status) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--profile"; fi ;;
        update) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--force"; fi ;;
        versions) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="list available get remove"; fi ;;
        pin) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--profile"; fi ;;
        unpin) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--profile"; fi ;;
        profiles) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="list new use remove"; fi ;;
        config) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="list get set unset path"; fi ;;
        flags) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="list get set unset import edit clear path --profile"; fi ;;
        plugins) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="list install remove enable disable grant revoke prefs deno --profile"; fi ;;
        doctor) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--offline"; fi ;;
        logs) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="--profile --path --lines"; fi ;;
        desktop) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="install remove status"; fi ;;
        completions) if (( COMP_CWORD == 2 )) || [[ $cur == -* ]]; then words="bash zsh fish"; fi ;;
        esac
    fi
    COMPREPLY=($(compgen -W "$words" -- "$cur"))
}
complete -F _stacked stacked
