# fish completion for stacked. Generated by `stacked completions fish`.
complete -c stacked -f
complete -c stacked -n __fish_use_subcommand -a play
complete -c stacked -n __fish_use_subcommand -a status
complete -c stacked -n __fish_use_subcommand -a install
complete -c stacked -n __fish_use_subcommand -a update
complete -c stacked -n __fish_use_subcommand -a versions
complete -c stacked -n __fish_use_subcommand -a pin
complete -c stacked -n __fish_use_subcommand -a unpin
complete -c stacked -n __fish_use_subcommand -a profiles
complete -c stacked -n __fish_use_subcommand -a config
complete -c stacked -n __fish_use_subcommand -a flags
complete -c stacked -n __fish_use_subcommand -a audio-outputs
complete -c stacked -n __fish_use_subcommand -a plugins
complete -c stacked -n __fish_use_subcommand -a doctor
complete -c stacked -n __fish_use_subcommand -a logs
complete -c stacked -n __fish_use_subcommand -a desktop
complete -c stacked -n __fish_use_subcommand -a completions
complete -c stacked -n __fish_use_subcommand -a diagnostics
complete -c stacked -n __fish_use_subcommand -a help
complete -c stacked -n __fish_use_subcommand -a version
complete -c stacked -n '__fish_seen_subcommand_from play' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from play' -l no-update
complete -c stacked -n '__fish_seen_subcommand_from play' -l run -r
complete -c stacked -n '__fish_seen_subcommand_from status' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from update' -l force
complete -c stacked -n '__fish_seen_subcommand_from versions; and test (count (commandline -opc)) -eq 2' -a 'list available get remove'
complete -c stacked -n '__fish_seen_subcommand_from pin' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from unpin' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from profiles; and test (count (commandline -opc)) -eq 2' -a 'list new use remove'
complete -c stacked -n '__fish_seen_subcommand_from config; and test (count (commandline -opc)) -eq 2' -a 'list get set unset path'
complete -c stacked -n '__fish_seen_subcommand_from flags; and test (count (commandline -opc)) -eq 2' -a 'list get set unset import edit clear path'
complete -c stacked -n '__fish_seen_subcommand_from flags' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from plugins; and test (count (commandline -opc)) -eq 2' -a 'list install remove enable disable grant revoke prefs deno'
complete -c stacked -n '__fish_seen_subcommand_from plugins' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from doctor' -l offline
complete -c stacked -n '__fish_seen_subcommand_from logs' -l profile -r -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from logs' -l path
complete -c stacked -n '__fish_seen_subcommand_from logs' -l lines
complete -c stacked -n '__fish_seen_subcommand_from desktop; and test (count (commandline -opc)) -eq 2' -a 'install remove status'
complete -c stacked -n '__fish_seen_subcommand_from completions; and test (count (commandline -opc)) -eq 2' -a 'bash zsh fish'
complete -c stacked -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get set unset' -a '(stacked __complete config-keys 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from profiles; and __fish_seen_subcommand_from use remove' -a '(stacked __complete profiles 2>/dev/null)'
complete -c stacked -n '__fish_seen_subcommand_from install import' -F
